version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/www/project/
permissions:
  - object: /home/ubuntu/www/
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: bash_scripts/clean_instance.sh
      timeout: 6000
      runas: root
  AfterInstall:
    - location: bash_scripts/install_os_dependencies.sh
      timeout: 6000
      runas: root
  ApplicationStart:
    - location: bash_scripts/start_application.sh
      timeout: 6000
      runas: ubuntu
  ApplicationStop:
    - location: bash_scripts/stop_application.sh
      timeout: 6000
      runas: ubuntu